### ISSUE TITLE
Check the existence of variables

### ISSUE THREAD

**Issue by danielsun1106** [tunnelvisionlabs/antlr4#26]
Hi Sam ( @sharwell  ),
      &nbsp;&nbsp;&nbsp;&nbsp; Could you please provide some method to check the existence of variables?
      &nbsp;&nbsp;&nbsp;&nbsp; For example, if I want to check whether rule `loopStatement` contains variable `footprint`, try-catch is required because `$loopStatement::footprint` will throw `NullPointerException` when rule `loopStatement` is not the parent rule of `continueStatement`(i.e. continue statement is not inside a loop statement). Though it can complete checking, it will also impact the performance of parsing.

```java
    try {
        $isInsideLoop = null != $loopStatement::footprint;
    } catch(NullPointerException e) {
        $isInsideLoop = false;
    }
```

**Complete code:**
https://github.com/apache/groovy/blob/master/src/main/antlr/GroovyParser.g4#L615-L634
```antlr
loopStatement
locals[ String footprint = "" ]
    :   FOR LPAREN forControl rparen nls statement                                                          #forStmtAlt
    |   WHILE expressionInPar nls statement                                                                   #whileStmtAlt
    |   DO nls statement nls WHILE expressionInPar                                                            #doWhileStmtAlt
    ;

continueStatement
locals[ boolean isInsideLoop ]
@init {
    try {
        $isInsideLoop = null != $loopStatement::footprint;
    } catch(NullPointerException e) {
        $isInsideLoop = false;
    }
}
    :   CONTINUE
        { require($isInsideLoop, "the continue statement is only allowed inside loops", -8); }
        identifier?
;
```

Cheers,
Daniel.Sun

**Comment by sharwell** [comment]
Interesting. Is there a reason you aren't checking this in a listener after the parse is complete? That typically gives the best error response.

**Comment by danielsun1106** [comment]
Sam, the new parser of Apache Groovy is based on visitor(not listener). 

https://github.com/apache/groovy/blob/master/subprojects/parser-antlr4/src/main/java/org/apache/groovy/parser/antlr4/AstBuilder.java#L151

P.S. I am not sure I have caught your words...

**Comment by danielsun1106** [comment]
I've managed to check while building AST :-)
