### ISSUE TITLE
Question: what is the difference between this project and antlr/antlr4

### ISSUE THREAD

**Issue by gfx** [tunnelvisionlabs/antlr4#5]
This project seems an old snapshot of https://github.com/antlr/antlr4, giving another artifact id with the same package name with https://github.com/antlr/antlr4.

However, @sharwell merged a pull-request (#2) in this project. Why? Does this project live?

**Comment by sharwell** [comment]
The original intent was for this project to be the main repository for the sharwell/optimized branch in my fork of antlr/antlr4. Since I'm not actively working on a project that uses ANTLR 4, it's on the back burner for now.

**Comment by gfx** [comment]
So I shouldn't use the artifact of this project?

My question comes from the fact that a Google official project, Android DataBinding, which is not an OSS yet, depends on `com.tunnelvisionlabs:antlr4` . I'll file an issue if there's no difference between this project and the official antlr4.

**Comment by sharwell** [comment]
The artifact you mentioned is published from my optimized fork, which contains quite a few performance improvements and features compared to the reference release. You can find the code in the sharwell/antlr4 repository.

**Comment by gfx** [comment]
I see. So there is a reason to use this project.

I'd like you to merge the difference to the original, or to change the package name from `org.antlr.v4`.

**Comment by sharwell** [comment]
Addressing the two concerns separately:

> change the package name from  org.antlr.v4

This would be a pretty major breaking change for existing users. Currently this artifact is compatible with the reference implementation for most grammars, even though the underlying prediction algorithm was completely rewritten. I want to make it as easy as possible to try out the different releases. Based on this, I see this change as extremely unlikely.

> I'd like you to merge the difference to the original

I'd like that too. However, I have limited time to work on the project and this is a *serious* undertaking:

1. My sharwell/optimized branch is 723 commits ahead of antlr/master. These changes were rejected from antlr/master for various reasons, but mostly the following:
  * Some features (e.g. *indirect* left recursion elimination and parse-tree preserving automated left factoring) are experimental and/or implemented only for a subset of the ANTLR 4 grammar language.
  * Some features (e.g. full context DFA, aggressive prediction context reduction, and stronger SLL termination conditions to reduce dynamic lookahead) are extremely complex while providing limited to no benefit for a majority of grammars in use. Most items in this category are performance optimizations for large, complex grammars used with very large inputs.
  * Some features have inconsistent impact on runtime scenarios. For example, the Boo grammar is practically unusable (speed and memory overhead) without the [enable_global_context_dfa](https://github.com/sharwell/antlr4/blob/700e9e57bc4e8e7d954419a37e04ecb39c30c1b5/runtime/Java/src/org/antlr/v4/runtime/atn/ParserATNSimulator.java#L319) flag set. For other grammars, setting this flag has the opposite effect. Communicating to users how to effectively use all the options in my fork is difficult, especially for new users.
2. My sharwell/optimized branch is 1326 commits behind antlr/master. Merging these changes into sharwell/optimized requires thorough evaluation of all algorithm changes to the runtime library in the context of my alternate implementation and additional functionality.

**Comment by gfx** [comment]
Thanks to the explanation. What the complex situation!
