### ISSUE TITLE
PHP Target

### ISSUE THREAD

**Issue by marcospassos** [tunnelvisionlabs/antlr4#76]
Hi @sharwell!

Do you consider supporting other targets? Can you give an idea of how much effort is needed to add support for a new target?

**Comment by sharwell** [comment]
There are no plans to create additional targets. Each target is an overwhelming amount of porting effort, requiring expert-level knowledge of low-level behaviors (internal runtime data structures, static and dynamic compilation characteristics, GC behavior, etc.) of _both_ Java and the new language.
